### ISSUE TITLE
[Bug] Papago: Unknown error: Unexpected translation error 'Invalid http response' - System.Net.WebException

### ISSUE THREAD

**Issue by frist008** [ramjke/Translumo#135]
Я думаю, что они обновили апи и приложению нужно обновление.

`Unknown error: Unexpected translation error 'Invalid http response'`

> 14:48:42.041 [ERR] Failed to check available versions
> System.InvalidOperationException: Failed to receive Version from Github
>  ---> System.Net.WebException: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера. [::ffff:10.0.0.1]:443 (api.github.com:443)
>  ---> System.Net.Http.HttpRequestException: Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера. [::ffff:10.0.0.1]:443 (api.github.com:443)
>  ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10060): Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера. [::ffff:10.0.0.1]:443
>    at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
>    at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
> --- End of stack trace from previous location ---
>    at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
>    at System.Net.Sockets.Socket.Connect(String host, Int32 port)
>    at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
>    at System.Net.HttpWebRequest.<>c__DisplayClass219_0.<<CreateHttpClient>b__1>d.MoveNext()
> --- End of stack trace from previous location ---
>    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
>    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellation(CancellationToken cancellationToken)
>    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
>    at System.Net.HttpWebRequest.SendRequest(Boolean async)
>    at System.Net.HttpWebRequest.GetResponse()
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.GetResponse()
>    at Translumo.Utils.Http.HttpReader.ReadWebData(WebRequest request, String dataIn, Boolean acceptCookie)
>    at Translumo.Utils.Http.HttpReader.RequestWebDataInternal(String url, HttpMethods method, String dataIn, Boolean acceptCookie)
>    --- End of inner exception stack trace ---
>    at Translumo.Update.GithubApiClient.GetReleasesAsync()
>    at Translumo.Update.GithubApiClient.GetLastVersionAsync()
>    at Translumo.Update.UpdateManager.CheckNewVersionAsync()
> 14:48:51.426 [ERR] Processing iteration failed due to unknown error
> System.InvalidOperationException: Unexpected translation error 'Invalid http response: '''
>  ---> System.Net.Http.HttpRequestException: Invalid http response: ''
>    at Translumo.Translation.Papago.PapagoReaderProxy.RequestAuthKeyAsync()
>    at Translumo.Translation.Papago.PapagoTranslator.TranslateTextInternal(PapagoContainer container, String sourceText)
>    at Translumo.Translation.BaseTranslator`1.TranslateTextAsync(String sourceText)
>    --- End of inner exception stack trace ---
>    at Translumo.Processing.TranslationProcessingService.TranslateInternal(CancellationToken cancellationToken)
>

**Comment by ramjke** [comment]
Removed in 1.1.0
